name: pixel_clash
description: Pixel Clash - мобильная игра на Flutter Flame
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Flame - игровой движок
  flame: 1.34.0

  # Для математических утилит/векторов (Flame использует Vector2)
  # (не обязательно добавлять отдельно, но пусть будет явно)
  vector_math: ^2.1.4
  drift: ^2.30.1
  drift_flutter: ^0.2.8
  sqlite3_flutter_libs: ^0.5.41
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.30.1
  build_runner: ^2.10.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
